[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "product-analyst-boundary-material-reader"
version = "0.1.0"
description = "description"
dependencies = [
    "sbilifeco-models-base>=0.1.3"
]